### ISSUE TITLE
Make direct download link

### ISSUE THREAD

**Issue by bartrylant** [olivierbon/craft-squeeze#1]
Would it be possible to make a direct download link to a zip file? Instead of having a user select which files he wants, just choose the files yourself and make a link.

**Comment by olivierbon** [comment]
Hey,

I'll do that soon, sorry, completely missed your message!

**Comment by bartrylant** [comment]
Cool! Looking forward to it. And just a question: would it be possible to rename files before zipping them?

**Comment by olivierbon** [comment]
Hey, just released an update so link download now works.
